const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const indexHtml = fs.readFileSync(path.join(__dirname, "..", "index.html"), "utf8");

test("Production UI messages avoid old English status text and object fallback", () => {
  const oldMessages = [
    "Saved package history: none",
    "Supabase insert succeeded",
    "Supabase update succeeded",
    "Supabase delete succeeded",
    "Tax package creation blocked",
    "Tax package delete blocked",
    "Evidence delete blocked",
    "AI extract failed",
    "[object Object]"
  ];

  for (const message of oldMessages) {
    assert.equal(indexHtml.includes(message), false, `${message} should not be shown in the UI`);
  }
});

test("Production UI contains Japanese operational status messages", () => {
  const expectedMessages = [
    "仕入を保存しました",
    "仕入を更新しました",
    "仕入を削除しました",
    "保存済みの税理士提出パッケージはありません",
    "税理士提出パッケージの作成には保存権限が必要です",
    "AI抽出に失敗しました"
  ];

  for (const message of expectedMessages) {
    assert.equal(indexHtml.includes(message), true, `${message} should be present in the UI`);
  }
});

test("Sales dashboard and Google Sheets controls stay visible", () => {
  const requiredControls = [
    'id="dashboardMonth"',
    'id="screenNav"',
    'id="manualEntryDetails"',
    "manual-entry-details",
    "ai-extract-panel",
    "openManualEntryForm",
    "その他海外サイト",
    "ヤフオク",
    "市場",
    "海外還付対象",
    "その他海外",
    "overseas_site",
    "domestic_other",
    'id="dashTaskBreakdown"',
    'id="salesFilterStaff"',
    'id="salesFilterText"',
    'id="salesQuickFilters"',
    'id="salesViewTabs"',
    'id="salesYearRevenue"',
    'id="salesMonthProfit"',
    'id="salesTaskList"',
    'id="salesDestinationProfitList"',
    "salesDestinationFilterDefinitions",
    "renderSalesQuickFilters",
    "salesViewDefinitions",
    "renderSalesViewTabs",
    "saleNeedsAttention",
    "renderSalesInsights",
    "managementNumber",
    "managementNumberFor",
    "generateManagementNumberForRecord",
    "buildManagementNumber",
    "managementSettings",
    "managementYahooLocationCode",
    "managementPhotographerCode",
    "managementBuyerCode",
    "managementPackingSize",
    "assignManagementNumbersToSelectedReviewItems",
    "assignReviewManagementNumbers",
    "generateManagementNumberBtn",
    "generateSaleListingId",
    "nextSaleBranchNumber",
    "generateSaleListingIdBtn",
    "MANAGEMENT_MONTH_CODES",
    "MANAGEMENT_NUMBER_MEMO_MARKER",
    "shiire_management_number:",
    'id="salePurchaseSearch"',
    'id="salePurchaseInventoryFilter"',
    "在庫ありを表示",
    "出品中在庫を表示",
    "在庫なしを表示",
    'id="selectVisibleSalesBtn"',
    'id="clearSelectedSalesBtn"',
    'id="salesBulkStatus"',
    'id="applySalesBulkStatusBtn"',
    'id="createMissingSalesBtn"',
    "applySalesBulkStatus",
    "saleToSaveInput",
    "createMissingSalesFromPurchases",
    "missingSalesPurchaseRecords",
    "saleDestinationFromPurchase",
    'id="managementNumber"',
    "仕入管理",
    "parseKnownCsvExtractText",
    "extractCsvBlocksFromText",
    "extractJsonObjectText",
    "readTextFileWithEncoding",
    "shift_jis",
    "scoreDecodedText",
    "item_name",
    "buy_total",
    "CSVから抽出",
    'id="syncSheetsBtn"',
    'id="extractDataFiles"',
    'id="extractFileList"',
    'id="invoiceRegistrationNumber"',
    "shiire_invoice_registration:",
    "EXTRACT_PARTNER_PROMPT",
    'accept="image/*,.csv,text/csv,application/pdf,.pdf"',
    'accept="image/*,application/pdf,.pdf"',
    "evidenceViewer",
    "evidence-pdf",
    'id="quickFilters"',
    'id="dashYearPurchaseQty"',
    'id="dashYearPurchaseAmount"',
    'id="dashYearRevenue"',
    'id="dashYearProfit"',
    "review-card",
    "review-fields",
    "review-bulk-tools",
    "review-supplier-tools",
    "review-selection-tools",
    "reviewSelectAll",
    "reviewSelectedIds",
    "selectedReviewItems",
    "toggleReviewSelection",
    "setAllReviewSelection",
    "data-review-select",
    "reviewSupplierPreset",
    "applySupplierToAllReviewItems",
    "SUPPLIER_PRESETS",
    "エコリング",
    "大吉",
    "data-review-copy-first",
    "data-review-set-all",
    "利用先をEBAYに全行へ反映",
    "setReviewFieldForAll",
    "copyFirstReviewFieldsToAll",
    "EXTRACT_PARTNER_PROMPT",
    "prepareExtractDataFiles",
    "prepareExtractFiles",
    "prepareExtractFiles(event.target.files)",
    "aiDocumentToEvidenceData",
    "getReviewEvidenceFiles",
    "state.aiDocuments.map(aiDocumentToEvidenceData)",
    'type: "document"',
    "clearSavedExtractDraft",
    "addExtractedTopBtn",
    "選択した行を一括登録",
    "setAddExtractedButtonText",
    "1件だけフォームで確認",
    "clearExtract",
    "担当者別 粗利",
    "販売先別 粗利",
    "在庫状態",
    "販売先だけでは在庫は変わりません",
    "saleInventoryLabel",
    "saleInventoryClass",
    "recordInventoryInfo",
    "daysSince",
    "isStaleStockRecord",
    "isStaleListedRecord",
    "inventory_stock",
    "inventory_listed",
    "inventory_sold",
    "stale_stock",
    "stale_listed",
    "仕入30日超",
    "出品30日超",
    "在庫経過日数",
    "長期在庫",
    "長期出品",
    "staleStockCount",
    "staleListedCount",
    "販売状況",
    "出品中在庫",
    "未処理タスク",
    "スプシへ送信",
    "quickFilterDefinitions",
    'id="purchaseSuggestion"',
    "purchase-suggestion",
    "過去データから候補を見つけました",
    "空欄を補完",
    "buildPurchaseSuggestion",
    "applyPurchaseSuggestion",
    "similarityScore",
    "normalizePredictText",
    "1. 商品情報",
    "2. 金額・税金",
    "3. 取引先情報",
    "review-delete-actions",
    "送料・手数料・税率だけ全行へ反映",
    'id="staffWorkflow"',
    "今日の作業",
    "仕入を登録",
    "販売を登録",
    "要確認を見る",
    "data-screen-shortcut",
    "日常業務ショートカット",
    'id="reviewPreflight"',
    "review-preflight",
    "登録可能だけ選択",
    "要確認も含めて選択",
    "reviewPreflightSummary",
    "setReviewSelectionByValidation",
    'id="recordCardList"',
    "record-card-list",
    "詳細表を表示",
    "renderRecordCards",
    'id="recordActionStatus"',
    "元に戻す",
    "restoreLastDeletedRecord",
    "restoreSupabaseRecord",
    "restorePurchase",
    "screenDefinitions",
    "証憑なし",
    "EVIDENCE_LABEL_OPTIONS",
    "data-proof-label",
    "evidenceLabel",
    "証憑種類",
    "自動",
    "evidenceLabelOptions",
    "updateFormProofLabel",
    "明細",
    "商品ページ",
    "請求書PDF",
    "現物写真",
    "旧クラウド同期（通常不要）",
    "旧同期を使う場合のみ入力",
    "全削除には管理者権限が必要です",
    "data-task-screen",
    "data-task-filter",
    "dashTaskBreakdown",
    "data-sales-issue",
    "saleMatchesIssue",
    "利益マイナス"
  ];

  for (const marker of requiredControls) {
    assert.equal(indexHtml.includes(marker), true, `${marker} should be present in the production UI`);
  }
});

test("Sales input validation prevents incomplete sold records", () => {
  const requiredMessages = [
    "売却済みの場合は販売日を入力してください",
    "売却済みの場合は販売価格を入力してください",
    "販売価格は0円以上で入力してください"
  ];

  for (const message of requiredMessages) {
    assert.equal(indexHtml.includes(message), true, `${message} should be present in sales validation`);
  }
});
